# Generated by Django 6.0.4 on 2026-05-12 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='org_type',
            field=models.CharField(choices=[('educational', 'Educational Institution'), ('company', 'Company / Organisation')], default='educational', help_text='Only relevant for admin accounts. Determines the system version shown in the dashboard.', max_length=20),
        ),
    ]
