# Generated by Django 6.0.4 on 2026-04-24 04:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('attendance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.CharField(choices=[('MEDICAL', 'Medical / Health'), ('FAMILY', 'Family Emergency'), ('PERSONAL', 'Personal Reason'), ('TRAVEL', 'Travel / Outstation'), ('OTHER', 'Other')], max_length=20)),
                ('description', models.TextField(blank=True, help_text='Additional details from the student/parent')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('proof_doc', models.FileField(blank=True, help_text='Medical certificate, letter, or any supporting document', null=True, upload_to='leave_proofs/')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10)),
                ('review_note', models.TextField(blank=True, help_text='Note from admin/teacher when approving or rejecting')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_leaves', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to='accounts.student')),
            ],
            options={
                'db_table': 'leave_requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
