# Generated by Django 6.0.4 on 2026-05-12 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_leaverequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaverequest',
            name='reason',
            field=models.CharField(choices=[('VACATION', 'Vacation'), ('SICK', 'Sick'), ('PERSONAL', 'Personal')], max_length=20),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('ATTENDANCE', 'Attendance'), ('ALERT', 'Alert'), ('SYSTEM', 'System')], default='ATTENDANCE', max_length=20),
        ),
    ]
